<?
//mots aléatoire pour publicite
$mots_clef_h2=array(1=>"Restauration-Japonaise-Commande-en-ligne","Livraison-à-domicile-gratuite"
,"livraison a domicile 75008"
,"livraison a domicile 75009"
,"livraison a domicile 75010"
,"livraison a domicile 75016"
,"livraison a domicile 75017"
,"livraison a domicile 75018"
,"livraison a domicile 75019"
,"livraison a domicile Saint-Ouen"
,"livraison a domicile Clichy"
,"livraison a domicile Levallois-Perret"
,"livraison a domicile Neuilly-sur-Seine"

,"commande en ligne 75008"
,"commande en ligne 75009"
,"commande en ligne 75010"
,"commande en ligne 75016"
,"commande en ligne 75017"
,"commande en ligne 75018"
,"commande en ligne 75019"
,"commande en ligne Saint-Ouen"
,"commande en ligne Clichy"
,"commande en ligne Levallois-Perret"
,"commande en ligne Neuilly-sur-Seine"

,"restaurant japonais 75008"
,"restaurant japonais 75009"
,"restaurant japonais 75010"
,"restaurant japonais 75016"
,"restaurant japonais 75017"
,"restaurant japonais 75018"
,"restaurant japonais 75019"
,"restaurant japonais Saint-Ouen"
,"restaurant japonais Clichy"
,"restaurant japonais Levallois-Perret"
,"restaurant japonais Neuilly-sur-Seine"

,"plat japonais 75008"
,"plat japonais 75009"
,"plat japonais 75010"
,"plat japonais 75016"
,"plat japonais 75017"
,"plat japonais 75018"
,"plat japonais 75019"
,"plat japonais Saint-Ouen"
,"plat japonais Clichy"
,"plat japonais Levallois-Perret"
,"plat japonais Neuilly-sur-Seine"

,"resto japonais 75008"
,"resto japonais 75009"
,"resto japonais 75010"
,"resto japonais 75016"
,"resto japonais 75017"
,"resto japonais 75018"
,"resto japonais 75019"
,"resto japonais Saint-Ouen"
,"resto japonais Clichy"
,"resto japonais Levallois-Perret"
,"resto japonais Neuilly-sur-Seine"

,"cuisine japonaise 75008"
,"cuisine japonaise 75009"
,"cuisine japonaise 75010"
,"cuisine japonaise 75016"
,"cuisine japonaise 75017"
,"cuisine japonaise 75018"
,"cuisine japonaise 75019"
,"cuisine japonaise Saint-Ouen"
,"cuisine japonaise Clichy"
,"cuisine japonaise Levallois-Perret"
,"cuisine japonaise Neuilly-sur-Seine"

,"sushi 75008"
,"sushi 75009"
,"sushi 75010"
,"sushi 75016"
,"sushi 75017"
,"sushi 75018"
,"sushi 75019"
,"sushi Saint-Ouen"
,"sushi Clichy"
,"sushi Levallois-Perret"
,"sushi Neuilly-sur-Seine"

,"restaurant japonais commande en ligne 75008"
,"restaurant japonais commande en ligne 75009"
,"restaurant japonais commande en ligne 75010"
,"restaurant japonais commande en ligne 75016"
,"restaurant japonais commande en ligne 75017"
,"restaurant japonais commande en ligne 75018"
,"restaurant japonais commande en ligne 75019"
,"restaurant japonais commande en ligne Saint-Ouen"
,"restaurant japonais commande en ligne Clichy"
,"restaurant japonais commande en ligne Levallois-Perret"
,"restaurant japonais commande en ligne Neuilly-sur-Seine"

,"resto japonais commande en ligne 75008"
,"resto japonais commande en ligne 75009"
,"resto japonais commande en ligne 75010"
,"resto japonais commande en ligne 75016"
,"resto japonais commande en ligne 75017"
,"resto japonais commande en ligne 75018"
,"resto japonais commande en ligne 75019"
,"resto japonais commande en ligne Saint-Ouen"
,"resto japonais commande en ligne Clichy"
,"resto japonais commande en ligne Levallois-Perret"
,"resto japonais commande en ligne Neuilly-sur-Seine"

,"cuisine japonaise commande en ligne 75008"
,"cuisine japonaise commande en ligne 75009"
,"cuisine japonaise commande en ligne 75010"
,"cuisine japonaise commande en ligne 75016"
,"cuisine japonaise commande en ligne 75017"
,"cuisine japonaise commande en ligne 75018"
,"cuisine japonaise commande en ligne 75019"
,"cuisine japonaise commande en ligne Saint-Ouen"
,"cuisine japonaise commande en ligne Clichy"
,"cuisine japonaise commande en ligne Levallois-Perret"
,"cuisine japonaise commande en ligne Neuilly-sur-Seine"

,"sushi commande en ligne 75008"
,"sushi commande en ligne 75009"
,"sushi commande en ligne 75010"
,"sushi commande en ligne 75016"
,"sushi commande en ligne 75017"
,"sushi commande en ligne 75018"
,"sushi commande en ligne 75019"
,"sushi commande en ligne Saint-Ouen"
,"sushi commande en ligne Clichy"
,"sushi commande en ligne Levallois-Perret"
,"sushi commande en ligne Neuilly-sur-Seine"

,"commande en ligne sushi 75008"
,"commande en ligne sushi 75009"
,"commande en ligne sushi 75010"
,"commande en ligne sushi 75016"
,"commande en ligne sushi 75017"
,"commande en ligne sushi 75018"
,"commande en ligne sushi 75019"
,"commande en ligne sushi Saint-Ouen"
,"commande en ligne sushi Clichy"
,"commande en ligne sushi Levallois-Perret"
,"commande en ligne sushi Neuilly-sur-Seine"

,"resto japonais commande en ligne 75008"
,"resto japonais commande en ligne 75009"
,"resto japonais commande en ligne 75010"
,"resto japonais commande en ligne 75016"
,"resto japonais commande en ligne 75017"
,"resto japonais commande en ligne 75018"
,"resto japonais commande en ligne 75019"
,"resto japonais commande en ligne Saint-Ouen"
,"resto japonais commande en ligne Clichy"
,"resto japonais commande en ligne Levallois-Perret"
,"resto japonais commande en ligne Neuilly-sur-Seine"

,"livraison a domicile restaurant japonais 75008"
,"livraison a domicile restaurant japonais 75009"
,"livraison a domicile restaurant japonais 75010"
,"livraison a domicile restaurant japonais 75016"
,"livraison a domicile restaurant japonais 75017"
,"livraison a domicile restaurant japonais 75018"
,"livraison a domicile restaurant japonais 75019"
,"livraison a domicile restaurant japonais Saint-Ouen"
,"livraison a domicile restaurant japonais Clichy"
,"livraison a domicile restaurant japonais Levallois-Perret"
,"livraison a domicile restaurant japonais Neuilly-sur-Seine"

,"commande en ligne resto japonais 75008"
,"commande en ligne resto japonais 75009"
,"commande en ligne resto japonais 75010"
,"commande en ligne resto japonais 75016"
,"commande en ligne resto japonais 75017"
,"commande en ligne resto japonais 75018"
,"commande en ligne resto japonais 75019"
,"commande en ligne resto japonais Saint-Ouen"
,"commande en ligne resto japonais Clichy"
,"commande en ligne resto japonais Levallois-Perret"
,"commande en ligne resto japonais Neuilly-sur-Seine"

,"livraison a domicile plat japonais 75008"
,"livraison a domicile plat japonais 75009"
,"livraison a domicile plat japonais 75010"
,"livraison a domicile plat japonais 75016"
,"livraison a domicile plat japonais 75017"
,"livraison a domicile plat japonais 75018"
,"livraison a domicile plat japonais 75019"
,"livraison a domicile plat japonais Saint-Ouen"
,"livraison a domicile plat japonais Clichy"
,"livraison a domicile plat japonais Levallois-Perret"
,"livraison a domicile plat japonais Neuilly-sur-Seine"

,"livraison a domicile cuisine japonais 75008"
,"livraison a domicile cuisine japonais 75009"
,"livraison a domicile cuisine japonais 75010"
,"livraison a domicile cuisine japonais 75016"
,"livraison a domicile cuisine japonais 75017"
,"livraison a domicile cuisine japonais 75018"
,"livraison a domicile cuisine japonais 75019"
,"livraison a domicile cuisine japonais Saint-Ouen"
,"livraison a domicile cuisine japonais Clichy"
,"livraison a domicile cuisine japonais Levallois-Perret"
,"livraison a domicile cuisine japonais Neuilly-sur-Seine"

,"livraison a domicile sushi 75008"
,"livraison a domicile sushi 75009"
,"livraison a domicile sushi 75010"
,"livraison a domicile sushi 75016"
,"livraison a domicile sushi 75017"
,"livraison a domicile sushi 75018"
,"livraison a domicile sushi 75019"
,"livraison a domicile sushi Saint-Ouen"
,"livraison a domicile sushi Clichy"
,"livraison a domicile sushi Levallois-Perret"
,"livraison a domicile sushi Neuilly-sur-Seine"

,"resto japonais livraison a domicile 75008"
,"resto japonais livraison a domicile 75009"
,"resto japonais livraison a domicile 75010"
,"resto japonais livraison a domicile 75016"
,"resto japonais livraison a domicile 75017"
,"resto japonais livraison a domicile 75018"
,"resto japonais livraison a domicile 75019"
,"resto japonais livraison a domicile Saint-Ouen"
,"resto japonais livraison a domicile Clichy"
,"resto japonais livraison a domicile Levallois-Perret"
,"resto japonais livraison a domicile Neuilly-sur-Seine"

,"plat japonais livraison a domicile 75008"
,"plat japonais livraison a domicile 75009"
,"plat japonais livraison a domicile 75010"
,"plat japonais livraison a domicile 75016"
,"plat japonais livraison a domicile 75017"
,"plat japonais livraison a domicile 75018"
,"plat japonais livraison a domicile 75019"
,"plat japonais livraison a domicile Saint-Ouen"
,"plat japonais livraison a domicile Clichy"
,"plat japonais livraison a domicile Levallois-Perret"
,"plat japonais livraison a domicile Neuilly-sur-Seine"

,"cuisine japonaise livraison a domicile 75008"
,"cuisine japonaise livraison a domicile 75009"
,"cuisine japonaise livraison a domicile 75010"
,"cuisine japonaise livraison a domicile 75016"
,"cuisine japonaise livraison a domicile 75017"
,"cuisine japonaise livraison a domicile 75018"
,"cuisine japonaise livraison a domicile 75019"
,"cuisine japonaise livraison a domicile Saint-Ouen"
,"cuisine japonaise livraison a domicile Clichy"
,"cuisine japonaise livraison a domicile Levallois-Perret"
,"cuisine japonaise livraison a domicile Neuilly-sur-Seine"

,"sushi livraison a domicile 75008"
,"sushi livraison a domicile 75009"
,"sushi livraison a domicile 75010"
,"sushi livraison a domicile 75016"
,"sushi livraison a domicile 75017"
,"sushi livraison a domicile 75018"
,"sushi livraison a domicile 75019"
,"sushi livraison a domicile Saint-Ouen"
,"sushi livraison a domicile Clichy"
,"sushi livraison a domicile Levallois-Perret"
,"sushi livraison a domicile Neuilly-sur-Seine"

,"livraison a domicile resto japonais 75008"
,"livraison a domicile resto japonais 75009"
,"livraison a domicile resto japonais 75010"
,"livraison a domicile resto japonais 75016"
,"livraison a domicile resto japonais 75017"
,"livraison a domicile resto japonais 75018"
,"livraison a domicile resto japonais 75019"
,"livraison a domicile resto japonais Saint-Ouen"
,"livraison a domicile resto japonais Clichy"
,"livraison a domicile resto japonais Levallois-Perret"
,"livraison a domicile resto japonais Neuilly-sur-Seine"

,"resto japonais livraison a domicile 75008"
,"resto japonais livraison a domicile 75009"
,"resto japonais livraison a domicile 75010"
,"resto japonais livraison a domicile 75016"
,"resto japonais livraison a domicile 75017"
,"resto japonais livraison a domicile 75018"
,"resto japonais livraison a domicile 75019"
,"resto japonais livraison a domicile Saint-Ouen"
,"resto japonais livraison a domicile Clichy"
,"resto japonais livraison a domicile Levallois-Perret"
,"resto japonais livraison a domicile Neuilly-sur-Seine"
);
$ln_car_pub = sizeof($mots_clef_h2);
$alea_mots_h2 = mt_rand(1,$ln_car_pub);
$KEYWORD_PUB=$mots_clef_pub[$alea_mots_pub];

//mots aléatoire
$mots_clef_h1=array(1=>"Restauration-Japonaise-Commande-en-ligne","Livraison-à-domicile-gratuite"
,"livraison a domicile 75008"
,"livraison a domicile 75009"
,"livraison a domicile 75010"
,"livraison a domicile 75016"
,"livraison a domicile 75017"
,"livraison a domicile 75018"
,"livraison a domicile 75019"
,"livraison a domicile Saint-Ouen"
,"livraison a domicile Clichy"
,"livraison a domicile Levallois-Perret"
,"livraison a domicile Neuilly-sur-Seine"

,"commande en ligne 75008"
,"commande en ligne 75009"
,"commande en ligne 75010"
,"commande en ligne 75016"
,"commande en ligne 75017"
,"commande en ligne 75018"
,"commande en ligne 75019"
,"commande en ligne Saint-Ouen"
,"commande en ligne Clichy"
,"commande en ligne Levallois-Perret"
,"commande en ligne Neuilly-sur-Seine"

,"restaurant japonais 75008"
,"restaurant japonais 75009"
,"restaurant japonais 75010"
,"restaurant japonais 75016"
,"restaurant japonais 75017"
,"restaurant japonais 75018"
,"restaurant japonais 75019"
,"restaurant japonais Saint-Ouen"
,"restaurant japonais Clichy"
,"restaurant japonais Levallois-Perret"
,"restaurant japonais Neuilly-sur-Seine"

,"plat japonais 75008"
,"plat japonais 75009"
,"plat japonais 75010"
,"plat japonais 75016"
,"plat japonais 75017"
,"plat japonais 75018"
,"plat japonais 75019"
,"plat japonais Saint-Ouen"
,"plat japonais Clichy"
,"plat japonais Levallois-Perret"
,"plat japonais Neuilly-sur-Seine"

,"resto japonais 75008"
,"resto japonais 75009"
,"resto japonais 75010"
,"resto japonais 75016"
,"resto japonais 75017"
,"resto japonais 75018"
,"resto japonais 75019"
,"resto japonais Saint-Ouen"
,"resto japonais Clichy"
,"resto japonais Levallois-Perret"
,"resto japonais Neuilly-sur-Seine"

,"cuisine japonaise 75008"
,"cuisine japonaise 75009"
,"cuisine japonaise 75010"
,"cuisine japonaise 75016"
,"cuisine japonaise 75017"
,"cuisine japonaise 75018"
,"cuisine japonaise 75019"
,"cuisine japonaise Saint-Ouen"
,"cuisine japonaise Clichy"
,"cuisine japonaise Levallois-Perret"
,"cuisine japonaise Neuilly-sur-Seine"

,"sushi 75008"
,"sushi 75009"
,"sushi 75010"
,"sushi 75016"
,"sushi 75017"
,"sushi 75018"
,"sushi 75019"
,"sushi Saint-Ouen"
,"sushi Clichy"
,"sushi Levallois-Perret"
,"sushi Neuilly-sur-Seine"

,"restaurant japonais commande en ligne 75008"
,"restaurant japonais commande en ligne 75009"
,"restaurant japonais commande en ligne 75010"
,"restaurant japonais commande en ligne 75016"
,"restaurant japonais commande en ligne 75017"
,"restaurant japonais commande en ligne 75018"
,"restaurant japonais commande en ligne 75019"
,"restaurant japonais commande en ligne Saint-Ouen"
,"restaurant japonais commande en ligne Clichy"
,"restaurant japonais commande en ligne Levallois-Perret"
,"restaurant japonais commande en ligne Neuilly-sur-Seine"

,"resto japonais commande en ligne 75008"
,"resto japonais commande en ligne 75009"
,"resto japonais commande en ligne 75010"
,"resto japonais commande en ligne 75016"
,"resto japonais commande en ligne 75017"
,"resto japonais commande en ligne 75018"
,"resto japonais commande en ligne 75019"
,"resto japonais commande en ligne Saint-Ouen"
,"resto japonais commande en ligne Clichy"
,"resto japonais commande en ligne Levallois-Perret"
,"resto japonais commande en ligne Neuilly-sur-Seine"

,"cuisine japonaise commande en ligne 75008"
,"cuisine japonaise commande en ligne 75009"
,"cuisine japonaise commande en ligne 75010"
,"cuisine japonaise commande en ligne 75016"
,"cuisine japonaise commande en ligne 75017"
,"cuisine japonaise commande en ligne 75018"
,"cuisine japonaise commande en ligne 75019"
,"cuisine japonaise commande en ligne Saint-Ouen"
,"cuisine japonaise commande en ligne Clichy"
,"cuisine japonaise commande en ligne Levallois-Perret"
,"cuisine japonaise commande en ligne Neuilly-sur-Seine"

,"sushi commande en ligne 75008"
,"sushi commande en ligne 75009"
,"sushi commande en ligne 75010"
,"sushi commande en ligne 75016"
,"sushi commande en ligne 75017"
,"sushi commande en ligne 75018"
,"sushi commande en ligne 75019"
,"sushi commande en ligne Saint-Ouen"
,"sushi commande en ligne Clichy"
,"sushi commande en ligne Levallois-Perret"
,"sushi commande en ligne Neuilly-sur-Seine"

,"commande en ligne sushi 75008"
,"commande en ligne sushi 75009"
,"commande en ligne sushi 75010"
,"commande en ligne sushi 75016"
,"commande en ligne sushi 75017"
,"commande en ligne sushi 75018"
,"commande en ligne sushi 75019"
,"commande en ligne sushi Saint-Ouen"
,"commande en ligne sushi Clichy"
,"commande en ligne sushi Levallois-Perret"
,"commande en ligne sushi Neuilly-sur-Seine"

,"resto japonais commande en ligne 75008"
,"resto japonais commande en ligne 75009"
,"resto japonais commande en ligne 75010"
,"resto japonais commande en ligne 75016"
,"resto japonais commande en ligne 75017"
,"resto japonais commande en ligne 75018"
,"resto japonais commande en ligne 75019"
,"resto japonais commande en ligne Saint-Ouen"
,"resto japonais commande en ligne Clichy"
,"resto japonais commande en ligne Levallois-Perret"
,"resto japonais commande en ligne Neuilly-sur-Seine"

,"livraison a domicile restaurant japonais 75008"
,"livraison a domicile restaurant japonais 75009"
,"livraison a domicile restaurant japonais 75010"
,"livraison a domicile restaurant japonais 75016"
,"livraison a domicile restaurant japonais 75017"
,"livraison a domicile restaurant japonais 75018"
,"livraison a domicile restaurant japonais 75019"
,"livraison a domicile restaurant japonais Saint-Ouen"
,"livraison a domicile restaurant japonais Clichy"
,"livraison a domicile restaurant japonais Levallois-Perret"
,"livraison a domicile restaurant japonais Neuilly-sur-Seine"

,"commande en ligne resto japonais 75008"
,"commande en ligne resto japonais 75009"
,"commande en ligne resto japonais 75010"
,"commande en ligne resto japonais 75016"
,"commande en ligne resto japonais 75017"
,"commande en ligne resto japonais 75018"
,"commande en ligne resto japonais 75019"
,"commande en ligne resto japonais Saint-Ouen"
,"commande en ligne resto japonais Clichy"
,"commande en ligne resto japonais Levallois-Perret"
,"commande en ligne resto japonais Neuilly-sur-Seine"

,"livraison a domicile plat japonais 75008"
,"livraison a domicile plat japonais 75009"
,"livraison a domicile plat japonais 75010"
,"livraison a domicile plat japonais 75016"
,"livraison a domicile plat japonais 75017"
,"livraison a domicile plat japonais 75018"
,"livraison a domicile plat japonais 75019"
,"livraison a domicile plat japonais Saint-Ouen"
,"livraison a domicile plat japonais Clichy"
,"livraison a domicile plat japonais Levallois-Perret"
,"livraison a domicile plat japonais Neuilly-sur-Seine"

,"livraison a domicile cuisine japonais 75008"
,"livraison a domicile cuisine japonais 75009"
,"livraison a domicile cuisine japonais 75010"
,"livraison a domicile cuisine japonais 75016"
,"livraison a domicile cuisine japonais 75017"
,"livraison a domicile cuisine japonais 75018"
,"livraison a domicile cuisine japonais 75019"
,"livraison a domicile cuisine japonais Saint-Ouen"
,"livraison a domicile cuisine japonais Clichy"
,"livraison a domicile cuisine japonais Levallois-Perret"
,"livraison a domicile cuisine japonais Neuilly-sur-Seine"

,"livraison a domicile sushi 75008"
,"livraison a domicile sushi 75009"
,"livraison a domicile sushi 75010"
,"livraison a domicile sushi 75016"
,"livraison a domicile sushi 75017"
,"livraison a domicile sushi 75018"
,"livraison a domicile sushi 75019"
,"livraison a domicile sushi Saint-Ouen"
,"livraison a domicile sushi Clichy"
,"livraison a domicile sushi Levallois-Perret"
,"livraison a domicile sushi Neuilly-sur-Seine"

,"resto japonais livraison a domicile 75008"
,"resto japonais livraison a domicile 75009"
,"resto japonais livraison a domicile 75010"
,"resto japonais livraison a domicile 75016"
,"resto japonais livraison a domicile 75017"
,"resto japonais livraison a domicile 75018"
,"resto japonais livraison a domicile 75019"
,"resto japonais livraison a domicile Saint-Ouen"
,"resto japonais livraison a domicile Clichy"
,"resto japonais livraison a domicile Levallois-Perret"
,"resto japonais livraison a domicile Neuilly-sur-Seine"

,"plat japonais livraison a domicile 75008"
,"plat japonais livraison a domicile 75009"
,"plat japonais livraison a domicile 75010"
,"plat japonais livraison a domicile 75016"
,"plat japonais livraison a domicile 75017"
,"plat japonais livraison a domicile 75018"
,"plat japonais livraison a domicile 75019"
,"plat japonais livraison a domicile Saint-Ouen"
,"plat japonais livraison a domicile Clichy"
,"plat japonais livraison a domicile Levallois-Perret"
,"plat japonais livraison a domicile Neuilly-sur-Seine"

,"cuisine japonaise livraison a domicile 75008"
,"cuisine japonaise livraison a domicile 75009"
,"cuisine japonaise livraison a domicile 75010"
,"cuisine japonaise livraison a domicile 75016"
,"cuisine japonaise livraison a domicile 75017"
,"cuisine japonaise livraison a domicile 75018"
,"cuisine japonaise livraison a domicile 75019"
,"cuisine japonaise livraison a domicile Saint-Ouen"
,"cuisine japonaise livraison a domicile Clichy"
,"cuisine japonaise livraison a domicile Levallois-Perret"
,"cuisine japonaise livraison a domicile Neuilly-sur-Seine"

,"sushi livraison a domicile 75008"
,"sushi livraison a domicile 75009"
,"sushi livraison a domicile 75010"
,"sushi livraison a domicile 75016"
,"sushi livraison a domicile 75017"
,"sushi livraison a domicile 75018"
,"sushi livraison a domicile 75019"
,"sushi livraison a domicile Saint-Ouen"
,"sushi livraison a domicile Clichy"
,"sushi livraison a domicile Levallois-Perret"
,"sushi livraison a domicile Neuilly-sur-Seine"

,"livraison a domicile resto japonais 75008"
,"livraison a domicile resto japonais 75009"
,"livraison a domicile resto japonais 75010"
,"livraison a domicile resto japonais 75016"
,"livraison a domicile resto japonais 75017"
,"livraison a domicile resto japonais 75018"
,"livraison a domicile resto japonais 75019"
,"livraison a domicile resto japonais Saint-Ouen"
,"livraison a domicile resto japonais Clichy"
,"livraison a domicile resto japonais Levallois-Perret"
,"livraison a domicile resto japonais Neuilly-sur-Seine"

,"resto japonais livraison a domicile 75008"
,"resto japonais livraison a domicile 75009"
,"resto japonais livraison a domicile 75010"
,"resto japonais livraison a domicile 75016"
,"resto japonais livraison a domicile 75017"
,"resto japonais livraison a domicile 75018"
,"resto japonais livraison a domicile 75019"
,"resto japonais livraison a domicile Saint-Ouen"
,"resto japonais livraison a domicile Clichy"
,"resto japonais livraison a domicile Levallois-Perret"
,"resto japonais livraison a domicile Neuilly-sur-Seine"
);
$ln_car = sizeof($mots_clef_h1);
$alea_mots_h1 = mt_rand(1,$ln_car);
?>